#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#define SIZEOF_IDIRECT3D9VTBL             68
#define OFFSETOF_IDIRECT3D9_CREATEDEVICE  64
#define INDEXOF_IDIRECT3D9_CREATEDEVICE (OFFSETOF_IDIRECT3D9_CREATEDEVICE / sizeof(void*))
#define SIZEOF_IDIRECT3DDEVICE9VTBL       476
#define SIZEOF_IDIRECT3D9EXVTBL           84
#define SIZEOF_IDIRECT3DDEVICE9EXVTBL     536

#define OFFSETOF_IDIRECT3DTEXTURE9_LOCKRECT 76
#define OFFSETOF_IDIRECT3DTEXTURE9_UNLOCKRECT 80

#ifdef __cplusplus
}
#endif

