//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 VertexPaint.rc 使用
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDS_PARAMS                      4
#define IDS_PAINTPROMPT                 5
#define IDS_RESTORE                     6
#define IDS_PAINT                       7
#define IDS_PICK                        8
#define IDS_STRING9                     9
#define IDS_CLASS_NAME_ORIGINAL         9
#define IDD_PANEL                       101
#define IDB_BUTTONS                     101
#define IDB_BUTTON_MASK                 102
#define IDC_PAINTCURSOR                 103
#define IDC_DROPPER_CURSOR              121
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define IDC_PAINT                       1001
#define IDC_PICK                        1002
#define IDC_VC_ON                       1004
#define IDC_SHADED                      1005
#define IDC_AFFECT_ALPHA                1006
#define IDC_AFFECT_COLOR                1009
#define IDC_AFFECT_ILLUM                1010
#define IDC_PICKOBJ                     1011
#define IDC_OBJLIST                     1012
#define IDC_COLOR                       1456
#define IDC_PALETTE_1                   1457
#define IDC_PALETTE_2                   1458
#define IDC_PALETTE_3                   1459
#define IDC_PALETTE_4                   1460
#define IDC_PALETTE_5                   1461
#define IDC_PALETTE_6                   1462
#define IDC_PALETTE_7                   1463
#define IDC_PALETTE_8                   1464
#define IDC_PALETTE_9                   1465
#define IDC_PALETTE_10                  1466
#define IDC_PALETTE_11                  1467
#define IDC_PALETTE_12                  1468
#define IDC_PALETTE_13                  1469
#define IDC_PALETTE_14                  1470
#define IDC_PALETTE_15                  1471
#define IDC_PALETTE_16                  1472
#define IDC_EDIT                        1490
#define IDC_SPIN                        1496
#define IDC_TINT                        3023
#define IDC_ALPHA                       3024
#define IDC_TINT_SPIN                   3028
#define IDC_ALPHA_SPIN                  3029

#define IDC_EN_SELBY_NORMAL             4043
#define IDC_EN_SELBY_VERTEX             4044
#define IDC_EN_SELBY_EDGE               4045
#define IDC_EN_SELBY_FACE               4046
#define IDC_EN_SELECT_BY_BOX            4047
#define IDC_EN_SHOW_HANDLES             4048
#define IDC_EN_TO_AVERAGE               4049
#define IDC_EN_USE_THRESHOLD            4050
#define IDC_EN_IGNORE_BACKFACING        4032
#define IDS_EDIT_NORMALS_MOD            40534
#define IDS_PARAMETERS                  40372
#define IDS_MOD_CATEGORY                40373
#define IDC_EN_COPY                     4135
#define IDC_EN_UNIFY                    4124
#define IDC_EN_BREAK                    4125
#define IDC_EN_RESET                    4126
#define IDC_EN_NUMBER_SEL               4127
#define IDC_EN_MAKE_EXPLICIT            4128
#define IDC_EN_AVERAGE                  4129
#define IDC_EN_TARGET_AVERAGE           4130
#define IDC_EN_TAR_AVERAGE_PIXELS_TEXT  4131
#define IDC_EN_AVERAGE_THRESHOLD        4132
#define IDC_EN_PASTE                    4033
#define IDC_EN_AVERAGE_THRESHOLD_SPIN   4034
#define IDC_EN_TAR_AVERAGE_BOX_SIZE_SPIN 4035
#define IDC_EN_TAR_AVERAGE_BOX_SIZE     4133
#define IDC_EN_SPECIFY                  4029
#define IDS_EN_AVERAGE                  40615
#define IDD_EDIT_NORMALS                666
#define IDS_EN_SELECT_BY                40601
#define IDS_EN_SHOW_HANDLES             40602
#define IDS_EN_IGNORE_BACKFACING        40540
#define IDS_EN_DISPLAY_LENGTH           40535
#define IDC_EN_LENGTH_SPIN              4030
#define IDC_EN_LENGTH                   4031
#define IDS_EN_EDIT_NORMALS_MODIFIER    40544
#define IDS_EN_SEL_LEVEL                40559
#define ID_EN_OBJECT_LEVEL              40076
#define ID_EN_NORMAL_LEVEL              40077
#define ID_EN_VERTEX_LEVEL              40078
#define ID_EN_EDGE_LEVEL                40079
#define ID_EN_FACE_LEVEL                40080
#define ID_EN_BREAK                     40121
#define ID_EN_UNIFY                     40122
#define ID_EN_SPECIFY                   40123
#define ID_EN_RESET                     40124
#define ID_EN_MAKE_EXPLICIT             40081
#define ID_EN_COPY                      40082
#define ID_EN_PASTE                     40083
#define ID_EN_AVERAGE                   40087
#define ID_EN_AVERAGE_MODE              40088
#define IDS_OBJECT_LEVEL                40548
#define IDS_VERTEX_LEVEL                40549
#define IDS_EDGE_LEVEL                  40550
#define IDS_FACE_LEVEL                  40551
#define IDS_EN_EDIT_NORMALS             40546
#define IDS_EN_NORMAL_LEVEL             40554
#define IDS_EN_BREAK                    40541
#define IDS_EN_UNIFY                    40542
#define IDS_EN_RESET                    40543
#define IDS_EN_SPECIFY                  40547
#define IDS_EN_MAKE_EXPLICIT            40555
#define IDS_EN_COPY                     40557
#define IDS_EN_AVERAGE_MODE             40616
#define IDR_ACCEL_EDIT_NORMALS          123
#define IDS_EN_PASTE                    40558
#define IDS_SELECT                      30778
#define IDS_EN_NORMAL                   40539
#define IDS_OBJECT_SEL                  30733
#define IDS_EN_WHICH_NORMAL_SELECTED    40538
#define IDS_EN_NUM_NORMALS_SELECTED     40536
#define IDC_EN_AVERAGE_BOX              4153
#define IDS_EDIT_VERTICES               40527
#define IDS_EDIT_EDGES                  40528
#define IDS_EDIT_FACES                  40529
#define IDS_REMOVE_VERTICES             40530
#define IDS_REMOVE_EDGES                40531
#define IDS_REMOVE                      40532
#define IDS_PICK_LIFT_EDGE              40533
#define IDS_EN_EDIT_NORMALS_MODDATA     40545
#define IDS_BORDER_LEVEL                40552
#define IDS_ELEMENT_LEVEL               40553
#define IDS_WELD_PIXELS                 40556


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
